#pragma config(Sensor, S1,     BWsensor,       sensorLightActive)
#pragma config(Sensor, S2,     RGBsensor,      sensorColorNxtRED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RBMIN 49	//Black
#define RBMAX 75	//White

#define RGBMIN 19	//Black
#define RGBMAX 56	//White

#define FACTOR 100

int leftSensor() // BWsensor
{
	float x = ((SensorValue[BWsensor] - RBMIN) / (RBMAX-RBMIN)) * FACTOR;
	return x;
}

int rightSensor() // RGBsensor
{
	float x = ((SensorValue[RGBsensor] - RGBMIN) / (RGBMAX-RGBMIN)) * FACTOR;
	return x;
}
